### ISSUE TITLE
Question about the InEKF

### ISSUE THREAD

**Issue by bereze** [manymuch/ground_normal_filter#1]
Hi, 请问一下，在代码中InEKF更新的观测是取累积旋转的最后一列，请问为什么是这样的呢？谢谢
`measure_vector = self.cumulative_rotation[:, 2]
  self.iekf.update("measure", measure_vector)`

**Comment by Jeongshi** [comment]
Hello, can this code be used directly in ROS melodic or in Open CV with ROS melodic?

**Comment by manymuch** [comment]
last column of the rotation matrix represents z vector
